// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteMeCommentsCommentIDReader is a Reader for the DeleteMeCommentsCommentID structure.
type DeleteMeCommentsCommentIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMeCommentsCommentIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMeCommentsCommentIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMeCommentsCommentIDOK creates a DeleteMeCommentsCommentIDOK with default headers values
func NewDeleteMeCommentsCommentIDOK() *DeleteMeCommentsCommentIDOK {
	return &DeleteMeCommentsCommentIDOK{}
}

/*DeleteMeCommentsCommentIDOK handles this case with default header values.

コメント削除の完了
*/
type DeleteMeCommentsCommentIDOK struct {
}

func (o *DeleteMeCommentsCommentIDOK) Error() string {
	return fmt.Sprintf("[DELETE /me/comments/{comment_id}][%d] deleteMeCommentsCommentIdOK ", 200)
}

func (o *DeleteMeCommentsCommentIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
