// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeArticlesArticleIDCommentsLikesParams creates a new GetMeArticlesArticleIDCommentsLikesParams object
// with the default values initialized.
func NewGetMeArticlesArticleIDCommentsLikesParams() *GetMeArticlesArticleIDCommentsLikesParams {
	var ()
	return &GetMeArticlesArticleIDCommentsLikesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeArticlesArticleIDCommentsLikesParamsWithTimeout creates a new GetMeArticlesArticleIDCommentsLikesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeArticlesArticleIDCommentsLikesParamsWithTimeout(timeout time.Duration) *GetMeArticlesArticleIDCommentsLikesParams {
	var ()
	return &GetMeArticlesArticleIDCommentsLikesParams{

		timeout: timeout,
	}
}

// NewGetMeArticlesArticleIDCommentsLikesParamsWithContext creates a new GetMeArticlesArticleIDCommentsLikesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeArticlesArticleIDCommentsLikesParamsWithContext(ctx context.Context) *GetMeArticlesArticleIDCommentsLikesParams {
	var ()
	return &GetMeArticlesArticleIDCommentsLikesParams{

		Context: ctx,
	}
}

// NewGetMeArticlesArticleIDCommentsLikesParamsWithHTTPClient creates a new GetMeArticlesArticleIDCommentsLikesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeArticlesArticleIDCommentsLikesParamsWithHTTPClient(client *http.Client) *GetMeArticlesArticleIDCommentsLikesParams {
	var ()
	return &GetMeArticlesArticleIDCommentsLikesParams{
		HTTPClient: client,
	}
}

/*GetMeArticlesArticleIDCommentsLikesParams contains all the parameters to send to the API endpoint
for the get me articles article ID comments likes operation typically these are written to a http.Request
*/
type GetMeArticlesArticleIDCommentsLikesParams struct {

	/*ArticleID
	  対象記事を指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) WithTimeout(timeout time.Duration) *GetMeArticlesArticleIDCommentsLikesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) WithContext(ctx context.Context) *GetMeArticlesArticleIDCommentsLikesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) WithHTTPClient(client *http.Client) *GetMeArticlesArticleIDCommentsLikesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) WithArticleID(articleID string) *GetMeArticlesArticleIDCommentsLikesParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get me articles article ID comments likes params
func (o *GetMeArticlesArticleIDCommentsLikesParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeArticlesArticleIDCommentsLikesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
