// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetArticlesArticleIDParams creates a new GetArticlesArticleIDParams object
// with the default values initialized.
func NewGetArticlesArticleIDParams() *GetArticlesArticleIDParams {
	var ()
	return &GetArticlesArticleIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetArticlesArticleIDParamsWithTimeout creates a new GetArticlesArticleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetArticlesArticleIDParamsWithTimeout(timeout time.Duration) *GetArticlesArticleIDParams {
	var ()
	return &GetArticlesArticleIDParams{

		timeout: timeout,
	}
}

// NewGetArticlesArticleIDParamsWithContext creates a new GetArticlesArticleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetArticlesArticleIDParamsWithContext(ctx context.Context) *GetArticlesArticleIDParams {
	var ()
	return &GetArticlesArticleIDParams{

		Context: ctx,
	}
}

// NewGetArticlesArticleIDParamsWithHTTPClient creates a new GetArticlesArticleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetArticlesArticleIDParamsWithHTTPClient(client *http.Client) *GetArticlesArticleIDParams {
	var ()
	return &GetArticlesArticleIDParams{
		HTTPClient: client,
	}
}

/*GetArticlesArticleIDParams contains all the parameters to send to the API endpoint
for the get articles article ID operation typically these are written to a http.Request
*/
type GetArticlesArticleIDParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get articles article ID params
func (o *GetArticlesArticleIDParams) WithTimeout(timeout time.Duration) *GetArticlesArticleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get articles article ID params
func (o *GetArticlesArticleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get articles article ID params
func (o *GetArticlesArticleIDParams) WithContext(ctx context.Context) *GetArticlesArticleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get articles article ID params
func (o *GetArticlesArticleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get articles article ID params
func (o *GetArticlesArticleIDParams) WithHTTPClient(client *http.Client) *GetArticlesArticleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get articles article ID params
func (o *GetArticlesArticleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get articles article ID params
func (o *GetArticlesArticleIDParams) WithArticleID(articleID string) *GetArticlesArticleIDParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get articles article ID params
func (o *GetArticlesArticleIDParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetArticlesArticleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
