// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetArticlesArticleIDAlistokenParams creates a new GetArticlesArticleIDAlistokenParams object
// with the default values initialized.
func NewGetArticlesArticleIDAlistokenParams() *GetArticlesArticleIDAlistokenParams {
	var ()
	return &GetArticlesArticleIDAlistokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetArticlesArticleIDAlistokenParamsWithTimeout creates a new GetArticlesArticleIDAlistokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetArticlesArticleIDAlistokenParamsWithTimeout(timeout time.Duration) *GetArticlesArticleIDAlistokenParams {
	var ()
	return &GetArticlesArticleIDAlistokenParams{

		timeout: timeout,
	}
}

// NewGetArticlesArticleIDAlistokenParamsWithContext creates a new GetArticlesArticleIDAlistokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetArticlesArticleIDAlistokenParamsWithContext(ctx context.Context) *GetArticlesArticleIDAlistokenParams {
	var ()
	return &GetArticlesArticleIDAlistokenParams{

		Context: ctx,
	}
}

// NewGetArticlesArticleIDAlistokenParamsWithHTTPClient creates a new GetArticlesArticleIDAlistokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetArticlesArticleIDAlistokenParamsWithHTTPClient(client *http.Client) *GetArticlesArticleIDAlistokenParams {
	var ()
	return &GetArticlesArticleIDAlistokenParams{
		HTTPClient: client,
	}
}

/*GetArticlesArticleIDAlistokenParams contains all the parameters to send to the API endpoint
for the get articles article ID alistoken operation typically these are written to a http.Request
*/
type GetArticlesArticleIDAlistokenParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) WithTimeout(timeout time.Duration) *GetArticlesArticleIDAlistokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) WithContext(ctx context.Context) *GetArticlesArticleIDAlistokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) WithHTTPClient(client *http.Client) *GetArticlesArticleIDAlistokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) WithArticleID(articleID string) *GetArticlesArticleIDAlistokenParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get articles article ID alistoken params
func (o *GetArticlesArticleIDAlistokenParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetArticlesArticleIDAlistokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
