// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCommentsCommentIDLikesParams creates a new GetCommentsCommentIDLikesParams object
// with the default values initialized.
func NewGetCommentsCommentIDLikesParams() *GetCommentsCommentIDLikesParams {
	var ()
	return &GetCommentsCommentIDLikesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCommentsCommentIDLikesParamsWithTimeout creates a new GetCommentsCommentIDLikesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCommentsCommentIDLikesParamsWithTimeout(timeout time.Duration) *GetCommentsCommentIDLikesParams {
	var ()
	return &GetCommentsCommentIDLikesParams{

		timeout: timeout,
	}
}

// NewGetCommentsCommentIDLikesParamsWithContext creates a new GetCommentsCommentIDLikesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCommentsCommentIDLikesParamsWithContext(ctx context.Context) *GetCommentsCommentIDLikesParams {
	var ()
	return &GetCommentsCommentIDLikesParams{

		Context: ctx,
	}
}

// NewGetCommentsCommentIDLikesParamsWithHTTPClient creates a new GetCommentsCommentIDLikesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCommentsCommentIDLikesParamsWithHTTPClient(client *http.Client) *GetCommentsCommentIDLikesParams {
	var ()
	return &GetCommentsCommentIDLikesParams{
		HTTPClient: client,
	}
}

/*GetCommentsCommentIDLikesParams contains all the parameters to send to the API endpoint
for the get comments comment ID likes operation typically these are written to a http.Request
*/
type GetCommentsCommentIDLikesParams struct {

	/*CommentID
	  対象コメントを指定するために使用

	*/
	CommentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) WithTimeout(timeout time.Duration) *GetCommentsCommentIDLikesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) WithContext(ctx context.Context) *GetCommentsCommentIDLikesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) WithHTTPClient(client *http.Client) *GetCommentsCommentIDLikesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommentID adds the commentID to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) WithCommentID(commentID string) *GetCommentsCommentIDLikesParams {
	o.SetCommentID(commentID)
	return o
}

// SetCommentID adds the commentId to the get comments comment ID likes params
func (o *GetCommentsCommentIDLikesParams) SetCommentID(commentID string) {
	o.CommentID = commentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCommentsCommentIDLikesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param comment_id
	if err := r.SetPathParam("comment_id", o.CommentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
