// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetUsersUserIDInfoReader is a Reader for the GetUsersUserIDInfo structure.
type GetUsersUserIDInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersUserIDInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersUserIDInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersUserIDInfoOK creates a GetUsersUserIDInfoOK with default headers values
func NewGetUsersUserIDInfoOK() *GetUsersUserIDInfoOK {
	return &GetUsersUserIDInfoOK{}
}

/*GetUsersUserIDInfoOK handles this case with default header values.

対象ユーザ情報
*/
type GetUsersUserIDInfoOK struct {
	Payload *models.UserInfo
}

func (o *GetUsersUserIDInfoOK) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/info][%d] getUsersUserIdInfoOK  %+v", 200, o.Payload)
}

func (o *GetUsersUserIDInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
