// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetTopicsReader is a Reader for the GetTopics structure.
type GetTopicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTopicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTopicsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTopicsOK creates a GetTopicsOK with default headers values
func NewGetTopicsOK() *GetTopicsOK {
	return &GetTopicsOK{}
}

/*GetTopicsOK handles this case with default header values.

トピックの一覧
*/
type GetTopicsOK struct {
	Payload []*models.Topic
}

func (o *GetTopicsOK) Error() string {
	return fmt.Sprintf("[GET /topics][%d] getTopicsOK  %+v", 200, o.Payload)
}

func (o *GetTopicsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
