// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsersUserIDArticlesPublicParams creates a new GetUsersUserIDArticlesPublicParams object
// with the default values initialized.
func NewGetUsersUserIDArticlesPublicParams() *GetUsersUserIDArticlesPublicParams {
	var ()
	return &GetUsersUserIDArticlesPublicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUserIDArticlesPublicParamsWithTimeout creates a new GetUsersUserIDArticlesPublicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersUserIDArticlesPublicParamsWithTimeout(timeout time.Duration) *GetUsersUserIDArticlesPublicParams {
	var ()
	return &GetUsersUserIDArticlesPublicParams{

		timeout: timeout,
	}
}

// NewGetUsersUserIDArticlesPublicParamsWithContext creates a new GetUsersUserIDArticlesPublicParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersUserIDArticlesPublicParamsWithContext(ctx context.Context) *GetUsersUserIDArticlesPublicParams {
	var ()
	return &GetUsersUserIDArticlesPublicParams{

		Context: ctx,
	}
}

// NewGetUsersUserIDArticlesPublicParamsWithHTTPClient creates a new GetUsersUserIDArticlesPublicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersUserIDArticlesPublicParamsWithHTTPClient(client *http.Client) *GetUsersUserIDArticlesPublicParams {
	var ()
	return &GetUsersUserIDArticlesPublicParams{
		HTTPClient: client,
	}
}

/*GetUsersUserIDArticlesPublicParams contains all the parameters to send to the API endpoint
for the get users user ID articles public operation typically these are written to a http.Request
*/
type GetUsersUserIDArticlesPublicParams struct {

	/*ArticleID
	  ページング処理における、現在のページの最後の記事のID

	*/
	ArticleID *string
	/*Limit
	  取得件数

	*/
	Limit *int64
	/*SortKey
	  ページング処理における、現在のページの最後の記事のソートキー

	*/
	SortKey *int64
	/*UserID
	  対象ユーザを指定するために使用

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithTimeout(timeout time.Duration) *GetUsersUserIDArticlesPublicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithContext(ctx context.Context) *GetUsersUserIDArticlesPublicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithHTTPClient(client *http.Client) *GetUsersUserIDArticlesPublicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithArticleID(articleID *string) *GetUsersUserIDArticlesPublicParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetArticleID(articleID *string) {
	o.ArticleID = articleID
}

// WithLimit adds the limit to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithLimit(limit *int64) *GetUsersUserIDArticlesPublicParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSortKey adds the sortKey to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithSortKey(sortKey *int64) *GetUsersUserIDArticlesPublicParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetSortKey(sortKey *int64) {
	o.SortKey = sortKey
}

// WithUserID adds the userID to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) WithUserID(userID string) *GetUsersUserIDArticlesPublicParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get users user ID articles public params
func (o *GetUsersUserIDArticlesPublicParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUserIDArticlesPublicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ArticleID != nil {

		// query param article_id
		var qrArticleID string
		if o.ArticleID != nil {
			qrArticleID = *o.ArticleID
		}
		qArticleID := qrArticleID
		if qArticleID != "" {
			if err := r.SetQueryParam("article_id", qArticleID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey int64
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := swag.FormatInt64(qrSortKey)
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
