// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetArticlesArticleIDAlistokenReader is a Reader for the GetArticlesArticleIDAlistoken structure.
type GetArticlesArticleIDAlistokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArticlesArticleIDAlistokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetArticlesArticleIDAlistokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetArticlesArticleIDAlistokenOK creates a GetArticlesArticleIDAlistokenOK with default headers values
func NewGetArticlesArticleIDAlistokenOK() *GetArticlesArticleIDAlistokenOK {
	return &GetArticlesArticleIDAlistokenOK{}
}

/*GetArticlesArticleIDAlistokenOK handles this case with default header values.

ALISトークン数
*/
type GetArticlesArticleIDAlistokenOK struct {
	Payload *GetArticlesArticleIDAlistokenOKBody
}

func (o *GetArticlesArticleIDAlistokenOK) Error() string {
	return fmt.Sprintf("[GET /articles/{article_id}/alistoken][%d] getArticlesArticleIdAlistokenOK  %+v", 200, o.Payload)
}

func (o *GetArticlesArticleIDAlistokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetArticlesArticleIDAlistokenOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetArticlesArticleIDAlistokenOKBody get articles article ID alistoken o k body
swagger:model GetArticlesArticleIDAlistokenOKBody
*/
type GetArticlesArticleIDAlistokenOKBody struct {

	// alistoken
	Alistoken float64 `json:"alistoken,omitempty"`
}

// Validate validates this get articles article ID alistoken o k body
func (o *GetArticlesArticleIDAlistokenOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetArticlesArticleIDAlistokenOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetArticlesArticleIDAlistokenOKBody) UnmarshalBinary(b []byte) error {
	var res GetArticlesArticleIDAlistokenOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
