// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetArticlesArticleIDLikesParams creates a new GetArticlesArticleIDLikesParams object
// with the default values initialized.
func NewGetArticlesArticleIDLikesParams() *GetArticlesArticleIDLikesParams {
	var ()
	return &GetArticlesArticleIDLikesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetArticlesArticleIDLikesParamsWithTimeout creates a new GetArticlesArticleIDLikesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetArticlesArticleIDLikesParamsWithTimeout(timeout time.Duration) *GetArticlesArticleIDLikesParams {
	var ()
	return &GetArticlesArticleIDLikesParams{

		timeout: timeout,
	}
}

// NewGetArticlesArticleIDLikesParamsWithContext creates a new GetArticlesArticleIDLikesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetArticlesArticleIDLikesParamsWithContext(ctx context.Context) *GetArticlesArticleIDLikesParams {
	var ()
	return &GetArticlesArticleIDLikesParams{

		Context: ctx,
	}
}

// NewGetArticlesArticleIDLikesParamsWithHTTPClient creates a new GetArticlesArticleIDLikesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetArticlesArticleIDLikesParamsWithHTTPClient(client *http.Client) *GetArticlesArticleIDLikesParams {
	var ()
	return &GetArticlesArticleIDLikesParams{
		HTTPClient: client,
	}
}

/*GetArticlesArticleIDLikesParams contains all the parameters to send to the API endpoint
for the get articles article ID likes operation typically these are written to a http.Request
*/
type GetArticlesArticleIDLikesParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) WithTimeout(timeout time.Duration) *GetArticlesArticleIDLikesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) WithContext(ctx context.Context) *GetArticlesArticleIDLikesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) WithHTTPClient(client *http.Client) *GetArticlesArticleIDLikesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) WithArticleID(articleID string) *GetArticlesArticleIDLikesParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get articles article ID likes params
func (o *GetArticlesArticleIDLikesParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetArticlesArticleIDLikesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
