// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeArticlesArticleIDLikeParams creates a new GetMeArticlesArticleIDLikeParams object
// with the default values initialized.
func NewGetMeArticlesArticleIDLikeParams() *GetMeArticlesArticleIDLikeParams {
	var ()
	return &GetMeArticlesArticleIDLikeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeArticlesArticleIDLikeParamsWithTimeout creates a new GetMeArticlesArticleIDLikeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeArticlesArticleIDLikeParamsWithTimeout(timeout time.Duration) *GetMeArticlesArticleIDLikeParams {
	var ()
	return &GetMeArticlesArticleIDLikeParams{

		timeout: timeout,
	}
}

// NewGetMeArticlesArticleIDLikeParamsWithContext creates a new GetMeArticlesArticleIDLikeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeArticlesArticleIDLikeParamsWithContext(ctx context.Context) *GetMeArticlesArticleIDLikeParams {
	var ()
	return &GetMeArticlesArticleIDLikeParams{

		Context: ctx,
	}
}

// NewGetMeArticlesArticleIDLikeParamsWithHTTPClient creates a new GetMeArticlesArticleIDLikeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeArticlesArticleIDLikeParamsWithHTTPClient(client *http.Client) *GetMeArticlesArticleIDLikeParams {
	var ()
	return &GetMeArticlesArticleIDLikeParams{
		HTTPClient: client,
	}
}

/*GetMeArticlesArticleIDLikeParams contains all the parameters to send to the API endpoint
for the get me articles article ID like operation typically these are written to a http.Request
*/
type GetMeArticlesArticleIDLikeParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) WithTimeout(timeout time.Duration) *GetMeArticlesArticleIDLikeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) WithContext(ctx context.Context) *GetMeArticlesArticleIDLikeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) WithHTTPClient(client *http.Client) *GetMeArticlesArticleIDLikeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) WithArticleID(articleID string) *GetMeArticlesArticleIDLikeParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get me articles article ID like params
func (o *GetMeArticlesArticleIDLikeParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeArticlesArticleIDLikeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
