// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetMeNotificationsReader is a Reader for the GetMeNotifications structure.
type GetMeNotificationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeNotificationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeNotificationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMeNotificationsOK creates a GetMeNotificationsOK with default headers values
func NewGetMeNotificationsOK() *GetMeNotificationsOK {
	return &GetMeNotificationsOK{}
}

/*GetMeNotificationsOK handles this case with default header values.

ログインユーザーの通知の一覧
*/
type GetMeNotificationsOK struct {
	Payload []*models.Notification
}

func (o *GetMeNotificationsOK) Error() string {
	return fmt.Sprintf("[GET /me/notifications][%d] getMeNotificationsOK  %+v", 200, o.Payload)
}

func (o *GetMeNotificationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
