// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetMeWalletBalanceReader is a Reader for the GetMeWalletBalance structure.
type GetMeWalletBalanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeWalletBalanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeWalletBalanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMeWalletBalanceOK creates a GetMeWalletBalanceOK with default headers values
func NewGetMeWalletBalanceOK() *GetMeWalletBalanceOK {
	return &GetMeWalletBalanceOK{}
}

/*GetMeWalletBalanceOK handles this case with default header values.

ログインユーザ情報
*/
type GetMeWalletBalanceOK struct {
	Payload *models.MeWalletBalance
}

func (o *GetMeWalletBalanceOK) Error() string {
	return fmt.Sprintf("[GET /me/wallet/balance][%d] getMeWalletBalanceOK  %+v", 200, o.Payload)
}

func (o *GetMeWalletBalanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MeWalletBalance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
