// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsersUserIDInfoParams creates a new GetUsersUserIDInfoParams object
// with the default values initialized.
func NewGetUsersUserIDInfoParams() *GetUsersUserIDInfoParams {
	var ()
	return &GetUsersUserIDInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUserIDInfoParamsWithTimeout creates a new GetUsersUserIDInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersUserIDInfoParamsWithTimeout(timeout time.Duration) *GetUsersUserIDInfoParams {
	var ()
	return &GetUsersUserIDInfoParams{

		timeout: timeout,
	}
}

// NewGetUsersUserIDInfoParamsWithContext creates a new GetUsersUserIDInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersUserIDInfoParamsWithContext(ctx context.Context) *GetUsersUserIDInfoParams {
	var ()
	return &GetUsersUserIDInfoParams{

		Context: ctx,
	}
}

// NewGetUsersUserIDInfoParamsWithHTTPClient creates a new GetUsersUserIDInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersUserIDInfoParamsWithHTTPClient(client *http.Client) *GetUsersUserIDInfoParams {
	var ()
	return &GetUsersUserIDInfoParams{
		HTTPClient: client,
	}
}

/*GetUsersUserIDInfoParams contains all the parameters to send to the API endpoint
for the get users user ID info operation typically these are written to a http.Request
*/
type GetUsersUserIDInfoParams struct {

	/*UserID
	  対象ユーザを指定するために使用

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users user ID info params
func (o *GetUsersUserIDInfoParams) WithTimeout(timeout time.Duration) *GetUsersUserIDInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users user ID info params
func (o *GetUsersUserIDInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users user ID info params
func (o *GetUsersUserIDInfoParams) WithContext(ctx context.Context) *GetUsersUserIDInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users user ID info params
func (o *GetUsersUserIDInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users user ID info params
func (o *GetUsersUserIDInfoParams) WithHTTPClient(client *http.Client) *GetUsersUserIDInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users user ID info params
func (o *GetUsersUserIDInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get users user ID info params
func (o *GetUsersUserIDInfoParams) WithUserID(userID string) *GetUsersUserIDInfoParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get users user ID info params
func (o *GetUsersUserIDInfoParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUserIDInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
