// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetMeArticlesArticleIDLikeReader is a Reader for the GetMeArticlesArticleIDLike structure.
type GetMeArticlesArticleIDLikeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeArticlesArticleIDLikeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeArticlesArticleIDLikeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMeArticlesArticleIDLikeOK creates a GetMeArticlesArticleIDLikeOK with default headers values
func NewGetMeArticlesArticleIDLikeOK() *GetMeArticlesArticleIDLikeOK {
	return &GetMeArticlesArticleIDLikeOK{}
}

/*GetMeArticlesArticleIDLikeOK handles this case with default header values.

対象記事に「いいね」を行ったかを判定
*/
type GetMeArticlesArticleIDLikeOK struct {
	Payload *GetMeArticlesArticleIDLikeOKBody
}

func (o *GetMeArticlesArticleIDLikeOK) Error() string {
	return fmt.Sprintf("[GET /me/articles/{article_id}/like][%d] getMeArticlesArticleIdLikeOK  %+v", 200, o.Payload)
}

func (o *GetMeArticlesArticleIDLikeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMeArticlesArticleIDLikeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetMeArticlesArticleIDLikeOKBody get me articles article ID like o k body
swagger:model GetMeArticlesArticleIDLikeOKBody
*/
type GetMeArticlesArticleIDLikeOKBody struct {

	// liked
	Liked bool `json:"liked,omitempty"`
}

// Validate validates this get me articles article ID like o k body
func (o *GetMeArticlesArticleIDLikeOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetMeArticlesArticleIDLikeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMeArticlesArticleIDLikeOKBody) UnmarshalBinary(b []byte) error {
	var res GetMeArticlesArticleIDLikeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
