// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetMeUnreadNotificationManagersReader is a Reader for the GetMeUnreadNotificationManagers structure.
type GetMeUnreadNotificationManagersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeUnreadNotificationManagersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeUnreadNotificationManagersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMeUnreadNotificationManagersOK creates a GetMeUnreadNotificationManagersOK with default headers values
func NewGetMeUnreadNotificationManagersOK() *GetMeUnreadNotificationManagersOK {
	return &GetMeUnreadNotificationManagersOK{}
}

/*GetMeUnreadNotificationManagersOK handles this case with default header values.

対象ユーザの通知未読情報
*/
type GetMeUnreadNotificationManagersOK struct {
	Payload *GetMeUnreadNotificationManagersOKBody
}

func (o *GetMeUnreadNotificationManagersOK) Error() string {
	return fmt.Sprintf("[GET /me/unread_notification_managers][%d] getMeUnreadNotificationManagersOK  %+v", 200, o.Payload)
}

func (o *GetMeUnreadNotificationManagersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMeUnreadNotificationManagersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetMeUnreadNotificationManagersOKBody get me unread notification managers o k body
swagger:model GetMeUnreadNotificationManagersOKBody
*/
type GetMeUnreadNotificationManagersOKBody struct {

	// unread
	Unread bool `json:"unread,omitempty"`
}

// Validate validates this get me unread notification managers o k body
func (o *GetMeUnreadNotificationManagersOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetMeUnreadNotificationManagersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMeUnreadNotificationManagersOKBody) UnmarshalBinary(b []byte) error {
	var res GetMeUnreadNotificationManagersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
