// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeArticlesArticleIDPublicParams creates a new GetMeArticlesArticleIDPublicParams object
// with the default values initialized.
func NewGetMeArticlesArticleIDPublicParams() *GetMeArticlesArticleIDPublicParams {
	var ()
	return &GetMeArticlesArticleIDPublicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeArticlesArticleIDPublicParamsWithTimeout creates a new GetMeArticlesArticleIDPublicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeArticlesArticleIDPublicParamsWithTimeout(timeout time.Duration) *GetMeArticlesArticleIDPublicParams {
	var ()
	return &GetMeArticlesArticleIDPublicParams{

		timeout: timeout,
	}
}

// NewGetMeArticlesArticleIDPublicParamsWithContext creates a new GetMeArticlesArticleIDPublicParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeArticlesArticleIDPublicParamsWithContext(ctx context.Context) *GetMeArticlesArticleIDPublicParams {
	var ()
	return &GetMeArticlesArticleIDPublicParams{

		Context: ctx,
	}
}

// NewGetMeArticlesArticleIDPublicParamsWithHTTPClient creates a new GetMeArticlesArticleIDPublicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeArticlesArticleIDPublicParamsWithHTTPClient(client *http.Client) *GetMeArticlesArticleIDPublicParams {
	var ()
	return &GetMeArticlesArticleIDPublicParams{
		HTTPClient: client,
	}
}

/*GetMeArticlesArticleIDPublicParams contains all the parameters to send to the API endpoint
for the get me articles article ID public operation typically these are written to a http.Request
*/
type GetMeArticlesArticleIDPublicParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) WithTimeout(timeout time.Duration) *GetMeArticlesArticleIDPublicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) WithContext(ctx context.Context) *GetMeArticlesArticleIDPublicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) WithHTTPClient(client *http.Client) *GetMeArticlesArticleIDPublicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) WithArticleID(articleID string) *GetMeArticlesArticleIDPublicParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get me articles article ID public params
func (o *GetMeArticlesArticleIDPublicParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeArticlesArticleIDPublicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
