// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeNotificationsParams creates a new GetMeNotificationsParams object
// with the default values initialized.
func NewGetMeNotificationsParams() *GetMeNotificationsParams {

	return &GetMeNotificationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeNotificationsParamsWithTimeout creates a new GetMeNotificationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeNotificationsParamsWithTimeout(timeout time.Duration) *GetMeNotificationsParams {

	return &GetMeNotificationsParams{

		timeout: timeout,
	}
}

// NewGetMeNotificationsParamsWithContext creates a new GetMeNotificationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeNotificationsParamsWithContext(ctx context.Context) *GetMeNotificationsParams {

	return &GetMeNotificationsParams{

		Context: ctx,
	}
}

// NewGetMeNotificationsParamsWithHTTPClient creates a new GetMeNotificationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeNotificationsParamsWithHTTPClient(client *http.Client) *GetMeNotificationsParams {

	return &GetMeNotificationsParams{
		HTTPClient: client,
	}
}

/*GetMeNotificationsParams contains all the parameters to send to the API endpoint
for the get me notifications operation typically these are written to a http.Request
*/
type GetMeNotificationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me notifications params
func (o *GetMeNotificationsParams) WithTimeout(timeout time.Duration) *GetMeNotificationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me notifications params
func (o *GetMeNotificationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me notifications params
func (o *GetMeNotificationsParams) WithContext(ctx context.Context) *GetMeNotificationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me notifications params
func (o *GetMeNotificationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me notifications params
func (o *GetMeNotificationsParams) WithHTTPClient(client *http.Client) *GetMeNotificationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me notifications params
func (o *GetMeNotificationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeNotificationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
