// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetArticlesRecentReader is a Reader for the GetArticlesRecent structure.
type GetArticlesRecentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArticlesRecentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetArticlesRecentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetArticlesRecentOK creates a GetArticlesRecentOK with default headers values
func NewGetArticlesRecentOK() *GetArticlesRecentOK {
	return &GetArticlesRecentOK{}
}

/*GetArticlesRecentOK handles this case with default header values.

最新記事一覧
*/
type GetArticlesRecentOK struct {
	Payload []*models.ArticleInfo
}

func (o *GetArticlesRecentOK) Error() string {
	return fmt.Sprintf("[GET /articles/recent][%d] getArticlesRecentOK  %+v", 200, o.Payload)
}

func (o *GetArticlesRecentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
