// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeUnreadNotificationManagersParams creates a new GetMeUnreadNotificationManagersParams object
// with the default values initialized.
func NewGetMeUnreadNotificationManagersParams() *GetMeUnreadNotificationManagersParams {

	return &GetMeUnreadNotificationManagersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeUnreadNotificationManagersParamsWithTimeout creates a new GetMeUnreadNotificationManagersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeUnreadNotificationManagersParamsWithTimeout(timeout time.Duration) *GetMeUnreadNotificationManagersParams {

	return &GetMeUnreadNotificationManagersParams{

		timeout: timeout,
	}
}

// NewGetMeUnreadNotificationManagersParamsWithContext creates a new GetMeUnreadNotificationManagersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeUnreadNotificationManagersParamsWithContext(ctx context.Context) *GetMeUnreadNotificationManagersParams {

	return &GetMeUnreadNotificationManagersParams{

		Context: ctx,
	}
}

// NewGetMeUnreadNotificationManagersParamsWithHTTPClient creates a new GetMeUnreadNotificationManagersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeUnreadNotificationManagersParamsWithHTTPClient(client *http.Client) *GetMeUnreadNotificationManagersParams {

	return &GetMeUnreadNotificationManagersParams{
		HTTPClient: client,
	}
}

/*GetMeUnreadNotificationManagersParams contains all the parameters to send to the API endpoint
for the get me unread notification managers operation typically these are written to a http.Request
*/
type GetMeUnreadNotificationManagersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me unread notification managers params
func (o *GetMeUnreadNotificationManagersParams) WithTimeout(timeout time.Duration) *GetMeUnreadNotificationManagersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me unread notification managers params
func (o *GetMeUnreadNotificationManagersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me unread notification managers params
func (o *GetMeUnreadNotificationManagersParams) WithContext(ctx context.Context) *GetMeUnreadNotificationManagersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me unread notification managers params
func (o *GetMeUnreadNotificationManagersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me unread notification managers params
func (o *GetMeUnreadNotificationManagersParams) WithHTTPClient(client *http.Client) *GetMeUnreadNotificationManagersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me unread notification managers params
func (o *GetMeUnreadNotificationManagersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeUnreadNotificationManagersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
