// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetMeInfoReader is a Reader for the GetMeInfo structure.
type GetMeInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMeInfoOK creates a GetMeInfoOK with default headers values
func NewGetMeInfoOK() *GetMeInfoOK {
	return &GetMeInfoOK{}
}

/*GetMeInfoOK handles this case with default header values.

ログインユーザ情報
*/
type GetMeInfoOK struct {
	Payload *models.UserInfo
}

func (o *GetMeInfoOK) Error() string {
	return fmt.Sprintf("[GET /me/info][%d] getMeInfoOK  %+v", 200, o.Payload)
}

func (o *GetMeInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
