// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetArticlesArticleIDCommentsReader is a Reader for the GetArticlesArticleIDComments structure.
type GetArticlesArticleIDCommentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArticlesArticleIDCommentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetArticlesArticleIDCommentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetArticlesArticleIDCommentsOK creates a GetArticlesArticleIDCommentsOK with default headers values
func NewGetArticlesArticleIDCommentsOK() *GetArticlesArticleIDCommentsOK {
	return &GetArticlesArticleIDCommentsOK{}
}

/*GetArticlesArticleIDCommentsOK handles this case with default header values.

対象記事のコメントの一覧
*/
type GetArticlesArticleIDCommentsOK struct {
	Payload *models.Comment
}

func (o *GetArticlesArticleIDCommentsOK) Error() string {
	return fmt.Sprintf("[GET /articles/{article_id}/comments][%d] getArticlesArticleIdCommentsOK  %+v", 200, o.Payload)
}

func (o *GetArticlesArticleIDCommentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Comment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
