// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetSearchArticlesReader is a Reader for the GetSearchArticles structure.
type GetSearchArticlesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSearchArticlesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSearchArticlesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSearchArticlesOK creates a GetSearchArticlesOK with default headers values
func NewGetSearchArticlesOK() *GetSearchArticlesOK {
	return &GetSearchArticlesOK{}
}

/*GetSearchArticlesOK handles this case with default header values.

検索記事一覧
*/
type GetSearchArticlesOK struct {
	Payload []*models.ArticleInfo
}

func (o *GetSearchArticlesOK) Error() string {
	return fmt.Sprintf("[GET /search/articles][%d] getSearchArticlesOK  %+v", 200, o.Payload)
}

func (o *GetSearchArticlesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
