// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// GetArticlesArticleIDReader is a Reader for the GetArticlesArticleID structure.
type GetArticlesArticleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArticlesArticleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetArticlesArticleIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetArticlesArticleIDOK creates a GetArticlesArticleIDOK with default headers values
func NewGetArticlesArticleIDOK() *GetArticlesArticleIDOK {
	return &GetArticlesArticleIDOK{}
}

/*GetArticlesArticleIDOK handles this case with default header values.

記事内容取得
*/
type GetArticlesArticleIDOK struct {
	Payload *models.ArticleContent
}

func (o *GetArticlesArticleIDOK) Error() string {
	return fmt.Sprintf("[GET /articles/{article_id}][%d] getArticlesArticleIdOK  %+v", 200, o.Payload)
}

func (o *GetArticlesArticleIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ArticleContent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
