// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeArticlesArticleIDPublicEditParams creates a new GetMeArticlesArticleIDPublicEditParams object
// with the default values initialized.
func NewGetMeArticlesArticleIDPublicEditParams() *GetMeArticlesArticleIDPublicEditParams {
	var ()
	return &GetMeArticlesArticleIDPublicEditParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeArticlesArticleIDPublicEditParamsWithTimeout creates a new GetMeArticlesArticleIDPublicEditParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeArticlesArticleIDPublicEditParamsWithTimeout(timeout time.Duration) *GetMeArticlesArticleIDPublicEditParams {
	var ()
	return &GetMeArticlesArticleIDPublicEditParams{

		timeout: timeout,
	}
}

// NewGetMeArticlesArticleIDPublicEditParamsWithContext creates a new GetMeArticlesArticleIDPublicEditParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeArticlesArticleIDPublicEditParamsWithContext(ctx context.Context) *GetMeArticlesArticleIDPublicEditParams {
	var ()
	return &GetMeArticlesArticleIDPublicEditParams{

		Context: ctx,
	}
}

// NewGetMeArticlesArticleIDPublicEditParamsWithHTTPClient creates a new GetMeArticlesArticleIDPublicEditParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeArticlesArticleIDPublicEditParamsWithHTTPClient(client *http.Client) *GetMeArticlesArticleIDPublicEditParams {
	var ()
	return &GetMeArticlesArticleIDPublicEditParams{
		HTTPClient: client,
	}
}

/*GetMeArticlesArticleIDPublicEditParams contains all the parameters to send to the API endpoint
for the get me articles article ID public edit operation typically these are written to a http.Request
*/
type GetMeArticlesArticleIDPublicEditParams struct {

	/*ArticleID
	  対象記事を指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) WithTimeout(timeout time.Duration) *GetMeArticlesArticleIDPublicEditParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) WithContext(ctx context.Context) *GetMeArticlesArticleIDPublicEditParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) WithHTTPClient(client *http.Client) *GetMeArticlesArticleIDPublicEditParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) WithArticleID(articleID string) *GetMeArticlesArticleIDPublicEditParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get me articles article ID public edit params
func (o *GetMeArticlesArticleIDPublicEditParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeArticlesArticleIDPublicEditParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
