// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetArticlesArticleIDLikesReader is a Reader for the GetArticlesArticleIDLikes structure.
type GetArticlesArticleIDLikesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArticlesArticleIDLikesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetArticlesArticleIDLikesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetArticlesArticleIDLikesOK creates a GetArticlesArticleIDLikesOK with default headers values
func NewGetArticlesArticleIDLikesOK() *GetArticlesArticleIDLikesOK {
	return &GetArticlesArticleIDLikesOK{}
}

/*GetArticlesArticleIDLikesOK handles this case with default header values.

対象記事の「いいね」数
*/
type GetArticlesArticleIDLikesOK struct {
	Payload *GetArticlesArticleIDLikesOKBody
}

func (o *GetArticlesArticleIDLikesOK) Error() string {
	return fmt.Sprintf("[GET /articles/{article_id}/likes][%d] getArticlesArticleIdLikesOK  %+v", 200, o.Payload)
}

func (o *GetArticlesArticleIDLikesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetArticlesArticleIDLikesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetArticlesArticleIDLikesOKBody get articles article ID likes o k body
swagger:model GetArticlesArticleIDLikesOKBody
*/
type GetArticlesArticleIDLikesOKBody struct {

	// count
	Count float64 `json:"count,omitempty"`
}

// Validate validates this get articles article ID likes o k body
func (o *GetArticlesArticleIDLikesOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetArticlesArticleIDLikesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetArticlesArticleIDLikesOKBody) UnmarshalBinary(b []byte) error {
	var res GetArticlesArticleIDLikesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
