// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeArticlesArticleIDDraftsParams creates a new GetMeArticlesArticleIDDraftsParams object
// with the default values initialized.
func NewGetMeArticlesArticleIDDraftsParams() *GetMeArticlesArticleIDDraftsParams {
	var ()
	return &GetMeArticlesArticleIDDraftsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeArticlesArticleIDDraftsParamsWithTimeout creates a new GetMeArticlesArticleIDDraftsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeArticlesArticleIDDraftsParamsWithTimeout(timeout time.Duration) *GetMeArticlesArticleIDDraftsParams {
	var ()
	return &GetMeArticlesArticleIDDraftsParams{

		timeout: timeout,
	}
}

// NewGetMeArticlesArticleIDDraftsParamsWithContext creates a new GetMeArticlesArticleIDDraftsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeArticlesArticleIDDraftsParamsWithContext(ctx context.Context) *GetMeArticlesArticleIDDraftsParams {
	var ()
	return &GetMeArticlesArticleIDDraftsParams{

		Context: ctx,
	}
}

// NewGetMeArticlesArticleIDDraftsParamsWithHTTPClient creates a new GetMeArticlesArticleIDDraftsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeArticlesArticleIDDraftsParamsWithHTTPClient(client *http.Client) *GetMeArticlesArticleIDDraftsParams {
	var ()
	return &GetMeArticlesArticleIDDraftsParams{
		HTTPClient: client,
	}
}

/*GetMeArticlesArticleIDDraftsParams contains all the parameters to send to the API endpoint
for the get me articles article ID drafts operation typically these are written to a http.Request
*/
type GetMeArticlesArticleIDDraftsParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) WithTimeout(timeout time.Duration) *GetMeArticlesArticleIDDraftsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) WithContext(ctx context.Context) *GetMeArticlesArticleIDDraftsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) WithHTTPClient(client *http.Client) *GetMeArticlesArticleIDDraftsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) WithArticleID(articleID string) *GetMeArticlesArticleIDDraftsParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the get me articles article ID drafts params
func (o *GetMeArticlesArticleIDDraftsParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeArticlesArticleIDDraftsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
