// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeArticlesArticleIDLikeReader is a Reader for the PostMeArticlesArticleIDLike structure.
type PostMeArticlesArticleIDLikeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeArticlesArticleIDLikeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeArticlesArticleIDLikeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeArticlesArticleIDLikeOK creates a PostMeArticlesArticleIDLikeOK with default headers values
func NewPostMeArticlesArticleIDLikeOK() *PostMeArticlesArticleIDLikeOK {
	return &PostMeArticlesArticleIDLikeOK{}
}

/*PostMeArticlesArticleIDLikeOK handles this case with default header values.

「いいね」の実施成功
*/
type PostMeArticlesArticleIDLikeOK struct {
}

func (o *PostMeArticlesArticleIDLikeOK) Error() string {
	return fmt.Sprintf("[POST /me/articles/{article_id}/like][%d] postMeArticlesArticleIdLikeOK ", 200)
}

func (o *PostMeArticlesArticleIDLikeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
