// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostMeArticlesArticleIDPvParams creates a new PostMeArticlesArticleIDPvParams object
// with the default values initialized.
func NewPostMeArticlesArticleIDPvParams() *PostMeArticlesArticleIDPvParams {
	var ()
	return &PostMeArticlesArticleIDPvParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMeArticlesArticleIDPvParamsWithTimeout creates a new PostMeArticlesArticleIDPvParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMeArticlesArticleIDPvParamsWithTimeout(timeout time.Duration) *PostMeArticlesArticleIDPvParams {
	var ()
	return &PostMeArticlesArticleIDPvParams{

		timeout: timeout,
	}
}

// NewPostMeArticlesArticleIDPvParamsWithContext creates a new PostMeArticlesArticleIDPvParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMeArticlesArticleIDPvParamsWithContext(ctx context.Context) *PostMeArticlesArticleIDPvParams {
	var ()
	return &PostMeArticlesArticleIDPvParams{

		Context: ctx,
	}
}

// NewPostMeArticlesArticleIDPvParamsWithHTTPClient creates a new PostMeArticlesArticleIDPvParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMeArticlesArticleIDPvParamsWithHTTPClient(client *http.Client) *PostMeArticlesArticleIDPvParams {
	var ()
	return &PostMeArticlesArticleIDPvParams{
		HTTPClient: client,
	}
}

/*PostMeArticlesArticleIDPvParams contains all the parameters to send to the API endpoint
for the post me articles article ID pv operation typically these are written to a http.Request
*/
type PostMeArticlesArticleIDPvParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) WithTimeout(timeout time.Duration) *PostMeArticlesArticleIDPvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) WithContext(ctx context.Context) *PostMeArticlesArticleIDPvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) WithHTTPClient(client *http.Client) *PostMeArticlesArticleIDPvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) WithArticleID(articleID string) *PostMeArticlesArticleIDPvParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the post me articles article ID pv params
func (o *PostMeArticlesArticleIDPvParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *PostMeArticlesArticleIDPvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
