// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeArticlesArticleIDPvReader is a Reader for the PostMeArticlesArticleIDPv structure.
type PostMeArticlesArticleIDPvReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeArticlesArticleIDPvReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeArticlesArticleIDPvOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeArticlesArticleIDPvOK creates a PostMeArticlesArticleIDPvOK with default headers values
func NewPostMeArticlesArticleIDPvOK() *PostMeArticlesArticleIDPvOK {
	return &PostMeArticlesArticleIDPvOK{}
}

/*PostMeArticlesArticleIDPvOK handles this case with default header values.

「閲覧」のカウント成功
*/
type PostMeArticlesArticleIDPvOK struct {
}

func (o *PostMeArticlesArticleIDPvOK) Error() string {
	return fmt.Sprintf("[POST /me/articles/{article_id}/pv][%d] postMeArticlesArticleIdPvOK ", 200)
}

func (o *PostMeArticlesArticleIDPvOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
