// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeArticlesDraftsReader is a Reader for the PostMeArticlesDrafts structure.
type PostMeArticlesDraftsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeArticlesDraftsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeArticlesDraftsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeArticlesDraftsOK creates a PostMeArticlesDraftsOK with default headers values
func NewPostMeArticlesDraftsOK() *PostMeArticlesDraftsOK {
	return &PostMeArticlesDraftsOK{}
}

/*PostMeArticlesDraftsOK handles this case with default header values.

作成された記事ID
*/
type PostMeArticlesDraftsOK struct {
	Payload *PostMeArticlesDraftsOKBody
}

func (o *PostMeArticlesDraftsOK) Error() string {
	return fmt.Sprintf("[POST /me/articles/drafts][%d] postMeArticlesDraftsOK  %+v", 200, o.Payload)
}

func (o *PostMeArticlesDraftsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostMeArticlesDraftsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostMeArticlesDraftsOKBody post me articles drafts o k body
swagger:model PostMeArticlesDraftsOKBody
*/
type PostMeArticlesDraftsOKBody struct {

	// article id
	ArticleID string `json:"article_id,omitempty"`
}

// Validate validates this post me articles drafts o k body
func (o *PostMeArticlesDraftsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMeArticlesDraftsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMeArticlesDraftsOKBody) UnmarshalBinary(b []byte) error {
	var res PostMeArticlesDraftsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
