// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostMeCommentsCommentIDLikesParams creates a new PostMeCommentsCommentIDLikesParams object
// with the default values initialized.
func NewPostMeCommentsCommentIDLikesParams() *PostMeCommentsCommentIDLikesParams {
	var ()
	return &PostMeCommentsCommentIDLikesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMeCommentsCommentIDLikesParamsWithTimeout creates a new PostMeCommentsCommentIDLikesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMeCommentsCommentIDLikesParamsWithTimeout(timeout time.Duration) *PostMeCommentsCommentIDLikesParams {
	var ()
	return &PostMeCommentsCommentIDLikesParams{

		timeout: timeout,
	}
}

// NewPostMeCommentsCommentIDLikesParamsWithContext creates a new PostMeCommentsCommentIDLikesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMeCommentsCommentIDLikesParamsWithContext(ctx context.Context) *PostMeCommentsCommentIDLikesParams {
	var ()
	return &PostMeCommentsCommentIDLikesParams{

		Context: ctx,
	}
}

// NewPostMeCommentsCommentIDLikesParamsWithHTTPClient creates a new PostMeCommentsCommentIDLikesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMeCommentsCommentIDLikesParamsWithHTTPClient(client *http.Client) *PostMeCommentsCommentIDLikesParams {
	var ()
	return &PostMeCommentsCommentIDLikesParams{
		HTTPClient: client,
	}
}

/*PostMeCommentsCommentIDLikesParams contains all the parameters to send to the API endpoint
for the post me comments comment ID likes operation typically these are written to a http.Request
*/
type PostMeCommentsCommentIDLikesParams struct {

	/*CommentID
	  対象コメントを指定するために使用

	*/
	CommentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) WithTimeout(timeout time.Duration) *PostMeCommentsCommentIDLikesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) WithContext(ctx context.Context) *PostMeCommentsCommentIDLikesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) WithHTTPClient(client *http.Client) *PostMeCommentsCommentIDLikesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommentID adds the commentID to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) WithCommentID(commentID string) *PostMeCommentsCommentIDLikesParams {
	o.SetCommentID(commentID)
	return o
}

// SetCommentID adds the commentId to the post me comments comment ID likes params
func (o *PostMeCommentsCommentIDLikesParams) SetCommentID(commentID string) {
	o.CommentID = commentID
}

// WriteToRequest writes these params to a swagger request
func (o *PostMeCommentsCommentIDLikesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param comment_id
	if err := r.SetPathParam("comment_id", o.CommentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
