// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeArticlesArticleIDFraudReader is a Reader for the PostMeArticlesArticleIDFraud structure.
type PostMeArticlesArticleIDFraudReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeArticlesArticleIDFraudReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeArticlesArticleIDFraudOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeArticlesArticleIDFraudOK creates a PostMeArticlesArticleIDFraudOK with default headers values
func NewPostMeArticlesArticleIDFraudOK() *PostMeArticlesArticleIDFraudOK {
	return &PostMeArticlesArticleIDFraudOK{}
}

/*PostMeArticlesArticleIDFraudOK handles this case with default header values.

不正報告の実施成功
*/
type PostMeArticlesArticleIDFraudOK struct {
}

func (o *PostMeArticlesArticleIDFraudOK) Error() string {
	return fmt.Sprintf("[POST /me/articles/{article_id}/fraud][%d] postMeArticlesArticleIdFraudOK ", 200)
}

func (o *PostMeArticlesArticleIDFraudOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
