// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeInfoIconReader is a Reader for the PostMeInfoIcon structure.
type PostMeInfoIconReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeInfoIconReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeInfoIconOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeInfoIconOK creates a PostMeInfoIconOK with default headers values
func NewPostMeInfoIconOK() *PostMeInfoIconOK {
	return &PostMeInfoIconOK{}
}

/*PostMeInfoIconOK handles this case with default header values.

登録した画像データのURL
*/
type PostMeInfoIconOK struct {
	Payload *PostMeInfoIconOKBody
}

func (o *PostMeInfoIconOK) Error() string {
	return fmt.Sprintf("[POST /me/info/icon][%d] postMeInfoIconOK  %+v", 200, o.Payload)
}

func (o *PostMeInfoIconOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostMeInfoIconOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostMeInfoIconOKBody post me info icon o k body
swagger:model PostMeInfoIconOKBody
*/
type PostMeInfoIconOKBody struct {

	// image url
	ImageURL string `json:"image_url,omitempty"`
}

// Validate validates this post me info icon o k body
func (o *PostMeInfoIconOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMeInfoIconOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMeInfoIconOKBody) UnmarshalBinary(b []byte) error {
	var res PostMeInfoIconOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
