// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// NewPostMeInfoIconParams creates a new PostMeInfoIconParams object
// with the default values initialized.
func NewPostMeInfoIconParams() *PostMeInfoIconParams {
	var ()
	return &PostMeInfoIconParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMeInfoIconParamsWithTimeout creates a new PostMeInfoIconParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMeInfoIconParamsWithTimeout(timeout time.Duration) *PostMeInfoIconParams {
	var ()
	return &PostMeInfoIconParams{

		timeout: timeout,
	}
}

// NewPostMeInfoIconParamsWithContext creates a new PostMeInfoIconParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMeInfoIconParamsWithContext(ctx context.Context) *PostMeInfoIconParams {
	var ()
	return &PostMeInfoIconParams{

		Context: ctx,
	}
}

// NewPostMeInfoIconParamsWithHTTPClient creates a new PostMeInfoIconParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMeInfoIconParamsWithHTTPClient(client *http.Client) *PostMeInfoIconParams {
	var ()
	return &PostMeInfoIconParams{
		HTTPClient: client,
	}
}

/*PostMeInfoIconParams contains all the parameters to send to the API endpoint
for the post me info icon operation typically these are written to a http.Request
*/
type PostMeInfoIconParams struct {

	/*Icon
	  icon object

	*/
	Icon *models.MeInfoIcon

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post me info icon params
func (o *PostMeInfoIconParams) WithTimeout(timeout time.Duration) *PostMeInfoIconParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post me info icon params
func (o *PostMeInfoIconParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post me info icon params
func (o *PostMeInfoIconParams) WithContext(ctx context.Context) *PostMeInfoIconParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post me info icon params
func (o *PostMeInfoIconParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post me info icon params
func (o *PostMeInfoIconParams) WithHTTPClient(client *http.Client) *PostMeInfoIconParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post me info icon params
func (o *PostMeInfoIconParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIcon adds the icon to the post me info icon params
func (o *PostMeInfoIconParams) WithIcon(icon *models.MeInfoIcon) *PostMeInfoIconParams {
	o.SetIcon(icon)
	return o
}

// SetIcon adds the icon to the post me info icon params
func (o *PostMeInfoIconParams) SetIcon(icon *models.MeInfoIcon) {
	o.Icon = icon
}

// WriteToRequest writes these params to a swagger request
func (o *PostMeInfoIconParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Icon != nil {
		if err := r.SetBodyParam(o.Icon); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
