// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostMeArticlesArticleIDLikeParams creates a new PostMeArticlesArticleIDLikeParams object
// with the default values initialized.
func NewPostMeArticlesArticleIDLikeParams() *PostMeArticlesArticleIDLikeParams {
	var ()
	return &PostMeArticlesArticleIDLikeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMeArticlesArticleIDLikeParamsWithTimeout creates a new PostMeArticlesArticleIDLikeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMeArticlesArticleIDLikeParamsWithTimeout(timeout time.Duration) *PostMeArticlesArticleIDLikeParams {
	var ()
	return &PostMeArticlesArticleIDLikeParams{

		timeout: timeout,
	}
}

// NewPostMeArticlesArticleIDLikeParamsWithContext creates a new PostMeArticlesArticleIDLikeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMeArticlesArticleIDLikeParamsWithContext(ctx context.Context) *PostMeArticlesArticleIDLikeParams {
	var ()
	return &PostMeArticlesArticleIDLikeParams{

		Context: ctx,
	}
}

// NewPostMeArticlesArticleIDLikeParamsWithHTTPClient creates a new PostMeArticlesArticleIDLikeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMeArticlesArticleIDLikeParamsWithHTTPClient(client *http.Client) *PostMeArticlesArticleIDLikeParams {
	var ()
	return &PostMeArticlesArticleIDLikeParams{
		HTTPClient: client,
	}
}

/*PostMeArticlesArticleIDLikeParams contains all the parameters to send to the API endpoint
for the post me articles article ID like operation typically these are written to a http.Request
*/
type PostMeArticlesArticleIDLikeParams struct {

	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) WithTimeout(timeout time.Duration) *PostMeArticlesArticleIDLikeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) WithContext(ctx context.Context) *PostMeArticlesArticleIDLikeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) WithHTTPClient(client *http.Client) *PostMeArticlesArticleIDLikeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) WithArticleID(articleID string) *PostMeArticlesArticleIDLikeParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the post me articles article ID like params
func (o *PostMeArticlesArticleIDLikeParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *PostMeArticlesArticleIDLikeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
