// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeArticlesArticleIDCommentsReader is a Reader for the PostMeArticlesArticleIDComments structure.
type PostMeArticlesArticleIDCommentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeArticlesArticleIDCommentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeArticlesArticleIDCommentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeArticlesArticleIDCommentsOK creates a PostMeArticlesArticleIDCommentsOK with default headers values
func NewPostMeArticlesArticleIDCommentsOK() *PostMeArticlesArticleIDCommentsOK {
	return &PostMeArticlesArticleIDCommentsOK{}
}

/*PostMeArticlesArticleIDCommentsOK handles this case with default header values.

コメント登録の完了
*/
type PostMeArticlesArticleIDCommentsOK struct {
	Payload *PostMeArticlesArticleIDCommentsOKBody
}

func (o *PostMeArticlesArticleIDCommentsOK) Error() string {
	return fmt.Sprintf("[POST /me/articles/{article_id}/comments][%d] postMeArticlesArticleIdCommentsOK  %+v", 200, o.Payload)
}

func (o *PostMeArticlesArticleIDCommentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostMeArticlesArticleIDCommentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostMeArticlesArticleIDCommentsOKBody post me articles article ID comments o k body
swagger:model PostMeArticlesArticleIDCommentsOKBody
*/
type PostMeArticlesArticleIDCommentsOKBody struct {

	// comment id
	CommentID string `json:"comment_id,omitempty"`
}

// Validate validates this post me articles article ID comments o k body
func (o *PostMeArticlesArticleIDCommentsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMeArticlesArticleIDCommentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMeArticlesArticleIDCommentsOKBody) UnmarshalBinary(b []byte) error {
	var res PostMeArticlesArticleIDCommentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
