// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMeCommentsCommentIDLikesReader is a Reader for the PostMeCommentsCommentIDLikes structure.
type PostMeCommentsCommentIDLikesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeCommentsCommentIDLikesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostMeCommentsCommentIDLikesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMeCommentsCommentIDLikesOK creates a PostMeCommentsCommentIDLikesOK with default headers values
func NewPostMeCommentsCommentIDLikesOK() *PostMeCommentsCommentIDLikesOK {
	return &PostMeCommentsCommentIDLikesOK{}
}

/*PostMeCommentsCommentIDLikesOK handles this case with default header values.

いいねの完了
*/
type PostMeCommentsCommentIDLikesOK struct {
}

func (o *PostMeCommentsCommentIDLikesOK) Error() string {
	return fmt.Sprintf("[POST /me/comments/{comment_id}/likes][%d] postMeCommentsCommentIdLikesOK ", 200)
}

func (o *PostMeCommentsCommentIDLikesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
