// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutMeArticlesArticleIDPublicUnpublishReader is a Reader for the PutMeArticlesArticleIDPublicUnpublish structure.
type PutMeArticlesArticleIDPublicUnpublishReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMeArticlesArticleIDPublicUnpublishReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutMeArticlesArticleIDPublicUnpublishOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMeArticlesArticleIDPublicUnpublishOK creates a PutMeArticlesArticleIDPublicUnpublishOK with default headers values
func NewPutMeArticlesArticleIDPublicUnpublishOK() *PutMeArticlesArticleIDPublicUnpublishOK {
	return &PutMeArticlesArticleIDPublicUnpublishOK{}
}

/*PutMeArticlesArticleIDPublicUnpublishOK handles this case with default header values.

successful operation
*/
type PutMeArticlesArticleIDPublicUnpublishOK struct {
}

func (o *PutMeArticlesArticleIDPublicUnpublishOK) Error() string {
	return fmt.Sprintf("[PUT /me/articles/{article_id}/public/unpublish][%d] putMeArticlesArticleIdPublicUnpublishOK ", 200)
}

func (o *PutMeArticlesArticleIDPublicUnpublishOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
