// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutMeArticlesArticleIDDraftsPublishReader is a Reader for the PutMeArticlesArticleIDDraftsPublish structure.
type PutMeArticlesArticleIDDraftsPublishReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMeArticlesArticleIDDraftsPublishReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutMeArticlesArticleIDDraftsPublishOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMeArticlesArticleIDDraftsPublishOK creates a PutMeArticlesArticleIDDraftsPublishOK with default headers values
func NewPutMeArticlesArticleIDDraftsPublishOK() *PutMeArticlesArticleIDDraftsPublishOK {
	return &PutMeArticlesArticleIDDraftsPublishOK{}
}

/*PutMeArticlesArticleIDDraftsPublishOK handles this case with default header values.

successful operation
*/
type PutMeArticlesArticleIDDraftsPublishOK struct {
}

func (o *PutMeArticlesArticleIDDraftsPublishOK) Error() string {
	return fmt.Sprintf("[PUT /me/articles/{article_id}/drafts/publish][%d] putMeArticlesArticleIdDraftsPublishOK ", 200)
}

func (o *PutMeArticlesArticleIDDraftsPublishOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
