// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutMeUnreadNotificationManagersParams creates a new PutMeUnreadNotificationManagersParams object
// with the default values initialized.
func NewPutMeUnreadNotificationManagersParams() *PutMeUnreadNotificationManagersParams {

	return &PutMeUnreadNotificationManagersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMeUnreadNotificationManagersParamsWithTimeout creates a new PutMeUnreadNotificationManagersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMeUnreadNotificationManagersParamsWithTimeout(timeout time.Duration) *PutMeUnreadNotificationManagersParams {

	return &PutMeUnreadNotificationManagersParams{

		timeout: timeout,
	}
}

// NewPutMeUnreadNotificationManagersParamsWithContext creates a new PutMeUnreadNotificationManagersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMeUnreadNotificationManagersParamsWithContext(ctx context.Context) *PutMeUnreadNotificationManagersParams {

	return &PutMeUnreadNotificationManagersParams{

		Context: ctx,
	}
}

// NewPutMeUnreadNotificationManagersParamsWithHTTPClient creates a new PutMeUnreadNotificationManagersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMeUnreadNotificationManagersParamsWithHTTPClient(client *http.Client) *PutMeUnreadNotificationManagersParams {

	return &PutMeUnreadNotificationManagersParams{
		HTTPClient: client,
	}
}

/*PutMeUnreadNotificationManagersParams contains all the parameters to send to the API endpoint
for the put me unread notification managers operation typically these are written to a http.Request
*/
type PutMeUnreadNotificationManagersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put me unread notification managers params
func (o *PutMeUnreadNotificationManagersParams) WithTimeout(timeout time.Duration) *PutMeUnreadNotificationManagersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put me unread notification managers params
func (o *PutMeUnreadNotificationManagersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put me unread notification managers params
func (o *PutMeUnreadNotificationManagersParams) WithContext(ctx context.Context) *PutMeUnreadNotificationManagersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put me unread notification managers params
func (o *PutMeUnreadNotificationManagersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put me unread notification managers params
func (o *PutMeUnreadNotificationManagersParams) WithHTTPClient(client *http.Client) *PutMeUnreadNotificationManagersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put me unread notification managers params
func (o *PutMeUnreadNotificationManagersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutMeUnreadNotificationManagersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
