// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/alisista/go-alis-client/models"
)

// NewPutMeArticlesArticleIDDraftsParams creates a new PutMeArticlesArticleIDDraftsParams object
// with the default values initialized.
func NewPutMeArticlesArticleIDDraftsParams() *PutMeArticlesArticleIDDraftsParams {
	var ()
	return &PutMeArticlesArticleIDDraftsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMeArticlesArticleIDDraftsParamsWithTimeout creates a new PutMeArticlesArticleIDDraftsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMeArticlesArticleIDDraftsParamsWithTimeout(timeout time.Duration) *PutMeArticlesArticleIDDraftsParams {
	var ()
	return &PutMeArticlesArticleIDDraftsParams{

		timeout: timeout,
	}
}

// NewPutMeArticlesArticleIDDraftsParamsWithContext creates a new PutMeArticlesArticleIDDraftsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMeArticlesArticleIDDraftsParamsWithContext(ctx context.Context) *PutMeArticlesArticleIDDraftsParams {
	var ()
	return &PutMeArticlesArticleIDDraftsParams{

		Context: ctx,
	}
}

// NewPutMeArticlesArticleIDDraftsParamsWithHTTPClient creates a new PutMeArticlesArticleIDDraftsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMeArticlesArticleIDDraftsParamsWithHTTPClient(client *http.Client) *PutMeArticlesArticleIDDraftsParams {
	var ()
	return &PutMeArticlesArticleIDDraftsParams{
		HTTPClient: client,
	}
}

/*PutMeArticlesArticleIDDraftsParams contains all the parameters to send to the API endpoint
for the put me articles article ID drafts operation typically these are written to a http.Request
*/
type PutMeArticlesArticleIDDraftsParams struct {

	/*Article
	  article object

	*/
	Article *models.MeArticlesDraftsCreate
	/*ArticleID
	  対象記事の指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) WithTimeout(timeout time.Duration) *PutMeArticlesArticleIDDraftsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) WithContext(ctx context.Context) *PutMeArticlesArticleIDDraftsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) WithHTTPClient(client *http.Client) *PutMeArticlesArticleIDDraftsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticle adds the article to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) WithArticle(article *models.MeArticlesDraftsCreate) *PutMeArticlesArticleIDDraftsParams {
	o.SetArticle(article)
	return o
}

// SetArticle adds the article to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) SetArticle(article *models.MeArticlesDraftsCreate) {
	o.Article = article
}

// WithArticleID adds the articleID to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) WithArticleID(articleID string) *PutMeArticlesArticleIDDraftsParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the put me articles article ID drafts params
func (o *PutMeArticlesArticleIDDraftsParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *PutMeArticlesArticleIDDraftsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Article != nil {
		if err := r.SetBodyParam(o.Article); err != nil {
			return err
		}
	}

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
