// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutMeArticlesArticleIDDraftsReader is a Reader for the PutMeArticlesArticleIDDrafts structure.
type PutMeArticlesArticleIDDraftsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMeArticlesArticleIDDraftsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutMeArticlesArticleIDDraftsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMeArticlesArticleIDDraftsOK creates a PutMeArticlesArticleIDDraftsOK with default headers values
func NewPutMeArticlesArticleIDDraftsOK() *PutMeArticlesArticleIDDraftsOK {
	return &PutMeArticlesArticleIDDraftsOK{}
}

/*PutMeArticlesArticleIDDraftsOK handles this case with default header values.

successful operation
*/
type PutMeArticlesArticleIDDraftsOK struct {
}

func (o *PutMeArticlesArticleIDDraftsOK) Error() string {
	return fmt.Sprintf("[PUT /me/articles/{article_id}/drafts][%d] putMeArticlesArticleIdDraftsOK ", 200)
}

func (o *PutMeArticlesArticleIDDraftsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
