// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutMeUnreadNotificationManagersReader is a Reader for the PutMeUnreadNotificationManagers structure.
type PutMeUnreadNotificationManagersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMeUnreadNotificationManagersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutMeUnreadNotificationManagersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMeUnreadNotificationManagersOK creates a PutMeUnreadNotificationManagersOK with default headers values
func NewPutMeUnreadNotificationManagersOK() *PutMeUnreadNotificationManagersOK {
	return &PutMeUnreadNotificationManagersOK{}
}

/*PutMeUnreadNotificationManagersOK handles this case with default header values.

successful operation
*/
type PutMeUnreadNotificationManagersOK struct {
}

func (o *PutMeUnreadNotificationManagersOK) Error() string {
	return fmt.Sprintf("[PUT /me/unread_notification_managers][%d] putMeUnreadNotificationManagersOK ", 200)
}

func (o *PutMeUnreadNotificationManagersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
