// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutMeArticlesArticleIDPublicReader is a Reader for the PutMeArticlesArticleIDPublic structure.
type PutMeArticlesArticleIDPublicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMeArticlesArticleIDPublicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutMeArticlesArticleIDPublicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMeArticlesArticleIDPublicOK creates a PutMeArticlesArticleIDPublicOK with default headers values
func NewPutMeArticlesArticleIDPublicOK() *PutMeArticlesArticleIDPublicOK {
	return &PutMeArticlesArticleIDPublicOK{}
}

/*PutMeArticlesArticleIDPublicOK handles this case with default header values.

successful operation
*/
type PutMeArticlesArticleIDPublicOK struct {
}

func (o *PutMeArticlesArticleIDPublicOK) Error() string {
	return fmt.Sprintf("[PUT /me/articles/{article_id}/public][%d] putMeArticlesArticleIdPublicOK ", 200)
}

func (o *PutMeArticlesArticleIDPublicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
