// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutMeArticlesArticleIDPublicUnpublishParams creates a new PutMeArticlesArticleIDPublicUnpublishParams object
// with the default values initialized.
func NewPutMeArticlesArticleIDPublicUnpublishParams() *PutMeArticlesArticleIDPublicUnpublishParams {
	var ()
	return &PutMeArticlesArticleIDPublicUnpublishParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMeArticlesArticleIDPublicUnpublishParamsWithTimeout creates a new PutMeArticlesArticleIDPublicUnpublishParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMeArticlesArticleIDPublicUnpublishParamsWithTimeout(timeout time.Duration) *PutMeArticlesArticleIDPublicUnpublishParams {
	var ()
	return &PutMeArticlesArticleIDPublicUnpublishParams{

		timeout: timeout,
	}
}

// NewPutMeArticlesArticleIDPublicUnpublishParamsWithContext creates a new PutMeArticlesArticleIDPublicUnpublishParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMeArticlesArticleIDPublicUnpublishParamsWithContext(ctx context.Context) *PutMeArticlesArticleIDPublicUnpublishParams {
	var ()
	return &PutMeArticlesArticleIDPublicUnpublishParams{

		Context: ctx,
	}
}

// NewPutMeArticlesArticleIDPublicUnpublishParamsWithHTTPClient creates a new PutMeArticlesArticleIDPublicUnpublishParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMeArticlesArticleIDPublicUnpublishParamsWithHTTPClient(client *http.Client) *PutMeArticlesArticleIDPublicUnpublishParams {
	var ()
	return &PutMeArticlesArticleIDPublicUnpublishParams{
		HTTPClient: client,
	}
}

/*PutMeArticlesArticleIDPublicUnpublishParams contains all the parameters to send to the API endpoint
for the put me articles article ID public unpublish operation typically these are written to a http.Request
*/
type PutMeArticlesArticleIDPublicUnpublishParams struct {

	/*ArticleID
	  対象記事を指定するために使用

	*/
	ArticleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) WithTimeout(timeout time.Duration) *PutMeArticlesArticleIDPublicUnpublishParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) WithContext(ctx context.Context) *PutMeArticlesArticleIDPublicUnpublishParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) WithHTTPClient(client *http.Client) *PutMeArticlesArticleIDPublicUnpublishParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArticleID adds the articleID to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) WithArticleID(articleID string) *PutMeArticlesArticleIDPublicUnpublishParams {
	o.SetArticleID(articleID)
	return o
}

// SetArticleID adds the articleId to the put me articles article ID public unpublish params
func (o *PutMeArticlesArticleIDPublicUnpublishParams) SetArticleID(articleID string) {
	o.ArticleID = articleID
}

// WriteToRequest writes these params to a swagger request
func (o *PutMeArticlesArticleIDPublicUnpublishParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param article_id
	if err := r.SetPathParam("article_id", o.ArticleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
