// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MeInfoUpdate me info update
// swagger:model MeInfoUpdate
type MeInfoUpdate struct {

	// self introduction
	SelfIntroduction string `json:"self_introduction,omitempty"`

	// user display name
	UserDisplayName string `json:"user_display_name,omitempty"`
}

// Validate validates this me info update
func (m *MeInfoUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MeInfoUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MeInfoUpdate) UnmarshalBinary(b []byte) error {
	var res MeInfoUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
